plugins:
  - rubocop-rspec

Layout/LineLength:
  Max: 100
  Exclude:
    - 'janus.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
